In [ ]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer 
from sklearn.compose import ColumnTransformer 
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [ ]:
df=pd.read_csv("C:\\Users\\jojic\\OneDrive\\Desktop\\mljourney\\feature-engineering\\encoding\\data\\Data.csv.xls")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 452.0+ bytes


In [192]:
df.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [193]:
X=df.iloc[:,:-1]
Y=df.iloc[:,-1]

In [194]:
df.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [195]:
#from sklearn.impute import SimpleImputer 
imputer=SimpleImputer(missing_values=np.nan,strategy="mean")
X.iloc[:,1:3]=imputer.fit_transform(X.iloc[:,1:3])

In [196]:
X

Country        Age        Salary
0   France  44.000000  72000.000000
1    Spain  27.000000  48000.000000
2  Germany  30.000000  54000.000000
3    Spain  38.000000  61000.000000
4  Germany  40.000000  63777.777778
5   France  35.000000  58000.000000
6    Spain  38.777778  52000.000000
7   France  48.000000  79000.000000
8  Germany  50.000000  83000.000000
9   France  37.000000  67000.000000

In [197]:
#from sklearn.compose import ColumnTransformer
#from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer([("encoder",OneHotEncoder(),[0])],remainder="passthrough")
X=pd.DataFrame(ct.fit_transform(X))
X

0    1    2          3             4
0  1.0  0.0  0.0  44.000000  72000.000000
1  0.0  0.0  1.0  27.000000  48000.000000
2  0.0  1.0  0.0  30.000000  54000.000000
3  0.0  0.0  1.0  38.000000  61000.000000
4  0.0  1.0  0.0  40.000000  63777.777778
5  1.0  0.0  0.0  35.000000  58000.000000
6  0.0  0.0  1.0  38.777778  52000.000000
7  1.0  0.0  0.0  48.000000  79000.000000
8  0.0  1.0  0.0  50.000000  83000.000000
9  1.0  0.0  0.0  37.000000  67000.000000

In [198]:
#from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
Y=le.fit_transform(Y)
Y 

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [199]:
#from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)

In [ ]:
#from sklearn.preprocessing import StandardScaler
scale=StandardScaler()
X_train=scale.fit_transform(X_train)
X_train

array([[-0.77459667, -0.57735027,  1.29099445, -1.62448414, -1.34688467],
       [ 1.29099445, -0.57735027, -0.77459667,  1.88440161,  2.03472003],
       [ 1.29099445, -0.57735027, -0.77459667, -0.28776576, -0.25604444],
       [-0.77459667, -0.57735027,  1.29099445,  0.21350363,  0.07120763],
       [-0.77459667,  1.73205081, -0.77459667,  0.54768323,  0.3742188 ],
       [ 1.29099445, -0.57735027, -0.77459667,  0.04641383,  0.72571176],
       [-0.77459667, -0.57735027,  1.29099445,  0.34346236, -0.91054858],
       [-0.77459667,  1.73205081, -0.77459667, -1.12321475, -0.69238053]])

In [ ]:
X_test=scale.fit(X_test)
X_test

array([[ 1., -1.,  0., -1., -1.],
       [-1.,  1.,  0.,  1.,  1.]])