In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler 
from sklearn.model_selection import train_test_split 

In [ ]:
df=pd.read_csv("C:\\Users\\jojic\\OneDrive\\Desktop\\mljourney\\feature-engineering\\intro\\student_data.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   StudentID          5000 non-null   int64  
 1   Age                5000 non-null   int64  
 2   Gender             5000 non-null   int64  
 3   Ethnicity          5000 non-null   int64  
 4   ParentalEducation  5000 non-null   int64  
 5   StudyTimeWeekly    5000 non-null   int64  
 6   Absences           5000 non-null   int64  
 7   Tutoring           5000 non-null   int64  
 8   ParentalSupport    5000 non-null   int64  
 9   Extracurricular    5000 non-null   int64  
 10  Sports             5000 non-null   int64  
 11  Music              5000 non-null   int64  
 12  Volunteering       5000 non-null   int64  
 13  GPA                5000 non-null   float64
 14  GradeClass         5000 non-null   int64  
dtypes: float64(1), int64(14)
memory usage: 586.1 KB


In [121]:
print(df.columns)
df.shape

Index(['StudentID', 'Age', 'Gender', 'Ethnicity', 'ParentalEducation',
       'StudyTimeWeekly', 'Absences', 'Tutoring', 'ParentalSupport',
       'Extracurricular', 'Sports', 'Music', 'Volunteering', 'GPA',
       'GradeClass'],
      dtype='object')


(5000, 15)

In [122]:
df.isnull().sum()

StudentID            0
Age                  0
Gender               0
Ethnicity            0
ParentalEducation    0
StudyTimeWeekly      0
Absences             0
Tutoring             0
ParentalSupport      0
Extracurricular      0
Sports               0
Music                0
Volunteering         0
GPA                  0
GradeClass           0
dtype: int64

In [123]:
#making every type similar
df["GPA"]=df["GPA"].astype("int")

In [124]:
df.dtypes

StudentID            int64
Age                  int64
Gender               int64
Ethnicity            int64
ParentalEducation    int64
StudyTimeWeekly      int64
Absences             int64
Tutoring             int64
ParentalSupport      int64
Extracurricular      int64
Sports               int64
Music                int64
Volunteering         int64
GPA                  int64
GradeClass           int64
dtype: object

In [125]:
df.head()

StudentID  Age  Gender  Ethnicity  ParentalEducation  StudyTimeWeekly  \
0       1001   17       1          1                  3               16   
1       1002   18       1          2                  0               17   
2       1003   15       1          0                  1               13   
3       1004   17       1          0                  3                6   
4       1005   17       0          1                  2                6   

   Absences  Tutoring  ParentalSupport  Extracurricular  Sports  Music  \
0        13         0                2                0       0      0   
1        28         0                2                1       1      1   
2        18         1                4                0       0      0   
3         4         0                3                1       0      0   
4        20         0                4                0       0      0   

   Volunteering  GPA  GradeClass  
0             0    3           1  
1             0    2           2  
2             1    3           0  
3             0    3           1  
4             0    3           1

In [126]:
df.drop(columns="StudentID",inplace=True)

In [127]:
df.head()

Age  Gender  Ethnicity  ParentalEducation  StudyTimeWeekly  Absences  \
0   17       1          1                  3               16        13   
1   18       1          2                  0               17        28   
2   15       1          0                  1               13        18   
3   17       1          0                  3                6         4   
4   17       0          1                  2                6        20   

   Tutoring  ParentalSupport  Extracurricular  Sports  Music  Volunteering  \
0         0                2                0       0      0             0   
1         0                2                1       1      1             0   
2         1                4                0       0      0             1   
3         0                3                1       0      0             0   
4         0                4                0       0      0             0   

   GPA  GradeClass  
0    3           1  
1    2           2  
2    3           0  
3    3           1  
4    3           1

In [128]:
#now we split x and y
X=df.iloc[:,:-1]
Y=df.iloc[:,-1]

In [129]:
X

Age  Gender  Ethnicity  ParentalEducation  StudyTimeWeekly  Absences  \
0      17       1          1                  3               16        13   
1      18       1          2                  0               17        28   
2      15       1          0                  1               13        18   
3      17       1          0                  3                6         4   
4      17       0          1                  2                6        20   
...   ...     ...        ...                ...              ...       ...   
4995   15       0          3                  2               12        22   
4996   16       0          1                  2                1         2   
4997   17       1          1                  3               18        18   
4998   16       0          2                  2               15         0   
4999   18       1          2                  4                4        23   

      Tutoring  ParentalSupport  Extracurricular  Sports  Music  Volunteering  \
0            0                2                0       0      0             0   
1            0                2                1       1      1             0   
2            1                4                0       0      0             1   
3            0                3                1       0      0             0   
4            0                4                0       0      0             0   
...        ...              ...              ...     ...    ...           ...   
4995         0                2                0       1      1             0   
4996         0                2                0       1      0             0   
4997         1                0                1       0      0             1   
4998         0                2                1       1      1             0   
4999         0                0                1       0      0             1   

      GPA  
0       3  
1       2  
2       3  
3       3  
4       3  
...   ...  
4995    4  
4996    2  
4997    4  
4998    4  
4999    2  

[5000 rows x 13 columns]

In [130]:
#from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
Xscaled=scaler.fit_transform(X)
Xscaled 

array([[0.66666667, 1.        , 0.33333333, ..., 0.        , 0.        ,
        0.5       ],
       [1.        , 1.        , 0.66666667, ..., 1.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.        , ..., 0.        , 1.        ,
        0.5       ],
       ...,
       [0.66666667, 1.        , 0.33333333, ..., 0.        , 1.        ,
        1.        ],
       [0.33333333, 0.        , 0.66666667, ..., 1.        , 0.        ,
        1.        ],
       [1.        , 1.        , 0.66666667, ..., 0.        , 1.        ,
        0.        ]], shape=(5000, 13))

In [131]:
#from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(Xscaled,Y,test_size=0.2)

In [132]:
X_train

array([[1.        , 1.        , 0.        , ..., 0.        , 1.        ,
        0.5       ],
       [1.        , 0.        , 0.        , ..., 0.        , 1.        ,
        1.        ],
       [0.66666667, 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.33333333, 1.        , 0.        , ..., 0.        , 1.        ,
        0.5       ],
       [0.66666667, 1.        , 1.        , ..., 0.        , 1.        ,
        0.5       ],
       [0.33333333, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]], shape=(4000, 13))

In [133]:
X_test

array([[0.        , 0.        , 0.33333333, ..., 1.        , 1.        ,
        1.        ],
       [1.        , 1.        , 0.        , ..., 0.        , 0.        ,
        1.        ],
       [0.66666667, 0.        , 0.        , ..., 0.        , 1.        ,
        1.        ],
       ...,
       [1.        , 1.        , 0.        , ..., 0.        , 0.        ,
        1.        ],
       [0.33333333, 0.        , 0.        , ..., 0.        , 0.        ,
        0.5       ],
       [0.33333333, 0.        , 0.66666667, ..., 1.        , 0.        ,
        0.5       ]], shape=(1000, 13))

In [ ]:
#encoding data into int
